name: CI

on:
  - push
  - pull_request   

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.4.x', '2.6.x' ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake spec
